// Sample dreams/bucket list data
const bucketList = [
  {
    id: 4,
    title: 'Build a successful tech startup',
    description: 'Create a product that impacts millions and leads a passionate team.',
    status: 'in-progress',
    goalType: 'Professional',
    progress: 60,
  },
  {
    id: 11,
    title: 'Receive recognition for tech contributions',
    description: 'Earn awards for significant contributions to technology.',
    status: 'not-started',
    goalType: 'Professional',
  },
  {
    id: 16,
    title: 'Create open-source software used by thousands',
    description: 'Develop open-source project with widespread adoption.',
    status: 'in-progress',
    goalType: 'Professional',
    progress: 25,
  },
  {
    id: 20,
    title: 'Be featured on tech/business magazine cover',
    description: 'Achieve recognition for magazine cover feature.',
    status: 'not-started',
    goalType: 'Professional',
  },
  {
    id: 21,
    title: 'Launch 2 successful startups before 30',
    description: 'Found and scale two successful ventures before 30.',
    status: 'in-progress',
    goalType: 'Professional',
    progress: 50,
  },
  {
    id: 23,
    title: 'Master advanced electronics',
    description: 'Develop expertise in electronics engineering.',
    status: 'not-started',
    goalType: 'Professional',
  },
  {
    id: 24,
    title: 'Create a hardware security lab',
    description: 'Build laboratory for hardware security research.',
    status: 'not-started',
    goalType: 'Professional',
  },
  {
    id: 27,
    title: 'Become a speaker at Black Hat USA',
    description: 'Present research at the premier cybersecurity conference.',
    status: 'not-started',
    goalType: 'Professional',
  },
  {
    id: 28,
    title: 'Design super cool PCB badges for conferences',
    description: 'Create custom PCB badges for at least 2 more conferences.',
    status: 'in-progress',
    goalType: 'Professional',
    progress: 30,
  },
  {
    id: 6,
    title: 'Travel to all 7 continents',
    description: 'Explore the diversity of our planet by visiting every continent.',
    status: 'not-started',
    goalType: 'Travel',
  },
  {
    id: 8,
    title: 'Visit 20 countries before turning 30',
    description: 'Explore diverse cultures across 20 different countries.',
    status: 'in-progress',
    goalType: 'Travel',
    progress: 5,
  },
  {
    id: 17,
    title: 'Bike across an entire country',
    description: 'Complete cross-country cycling journey.',
    status: 'not-started',
    goalType: 'Travel',
  },
  {
    id: 18,
    title: 'Road trip from Kerala to Africa',
    description: 'Epic overland journey from Kerala to Africa.',
    status: 'not-started',
    goalType: 'Travel',
  },
  {
    id: 19,
    title: 'Cross African continent by car',
    description: 'Drive across entire African continent.',
    status: 'not-started',
    goalType: 'Travel',
  },

  {
    id: 9,
    title: 'Achieve peak male physique',
    description: 'Build exceptional physical fitness and muscular development.',
    status: 'in-progress',
    goalType: 'Health',
    progress: 40,
  },
  {
    id: 10,
    title: 'Master advanced calisthenics',
    description: 'Learn advanced bodyweight exercises like planche and muscle-ups.',
    status: 'not-started',
    goalType: 'Health',
  },
  {
    id: 3,
    title: 'Skydive from 15,000 feet',
    description: 'Experience the thrill of freefall and conquer fear of heights.',
    status: 'not-started',
    goalType: 'Experience',
  },
  {
    id: 12,
    title: 'Solo backpacking adventure to remote destination',
    description: 'Embark on a challenging solo journey to isolated locations.',
    status: 'not-started',
    goalType: 'Experience',
  },
  {
    id: 13,
    title: 'Become certified Advanced Open Water Diver',
    description: 'Achieve advanced scuba diving certification.',
    status: 'not-started',
    goalType: 'Experience',
  },
  {
    id: 14,
    title: 'Become certified skydiver',
    description: 'Complete skydiving certification for solo jumps.',
    status: 'not-started',
    goalType: 'Experience',
  },
  {
    id: 25,
    title: 'Do bungee jump',
    description: 'Experience the thrill of bungee jumping.',
    status: 'not-started',
    goalType: 'Experience',
  },
  {
    id: 26,
    title: 'Trek to Everest base camp',
    description: 'Complete the challenging trek to Everest base camp.',
    status: 'not-started',
    goalType: 'Experience',
  },

  {
    id: 15,
    title: 'Join Territorial Army',
    description: 'Serve in Territorial Army while maintaining civilian career.',
    status: 'not-started',
    goalType: 'Personal',
  },
];

export default bucketList; 